#!/bin/sh

# if the branch is master, then fail.
branch="$(git symbolic-ref HEAD 2>/dev/null)" || "$(git describe --contains --all HEAD)"
if [ "${branch##refs/heads/}" = "master" ]; then
    echo "error: SHOULD NOT push to the master branch!"
    echo "If you really want to push to the master branch, please run 'git push --no-verify'."
    exit 1
fi
