#!/bin/sh

if [ -z "$(git config --local user.name)" ]; then
    echo "error: user.name isn't set locally!"
    exit 1
fi
if [ -z "$(git config --local user.email)" ]; then
    echo "error: user.email isn't set locally!"
    exit 1
fi
